# Generated by Django 5.1.3 on 2025-07-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
